from __future__ import annotations


DEFAULT_SELLER_RULES = [
    {
        "rule_id": "SELLER_TOP_3_SALES",
        "version": 1,
        "priority": 95,
        "category": "strength",
        "condition": {"metric": "rankSales", "operator": "lte", "value": 3},
        "message_template": "Está en el puesto {rankSales} del ranking de venta neta.",
        "action_template": "Identificar y documentar las prácticas que sostienen el resultado.",
        "evidence_fields": ["rankSales", "sales"],
        "conflict_group": "sales_rank",
    },
    {
        "rule_id": "SELLER_RANKING_IMPROVEMENT",
        "version": 1,
        "priority": 90,
        "category": "strength",
        "condition": {"metric": "rankDelta", "operator": "gte", "value": 1},
        "message_template": "Mejoró {rankDelta} posiciones y ahora ocupa el puesto {rankSales}.",
        "action_template": "Sostener las palancas que explican la mejora de posición.",
        "evidence_fields": ["rankDelta", "rankSales", "previousRankSales"],
        "conflict_group": "sales_rank",
    },
    {
        "rule_id": "SELLER_GROWTH_ABOVE_TEAM",
        "version": 1,
        "priority": 88,
        "category": "strength",
        "condition": {"metric": "growthPct", "operator": "gte_context", "context": "teamGrowthPct"},
        "message_template": "La venta creció {growthPct:.1f}%, frente a {teamGrowthPct:.1f}% del equipo.",
        "action_template": "Repetir las prácticas de crecimiento en las rutas con mayor potencial.",
        "evidence_fields": ["growthPct", "teamGrowthPct"],
        "conflict_group": "growth",
    },
    {
        "rule_id": "SELLER_SALES_DROP",
        "version": 1,
        "priority": 92,
        "category": "opportunity",
        "condition": {"metric": "growthPct", "operator": "lte", "value": -10},
        "message_template": "La venta cayó {growthPct:.1f}% contra el período comparativo.",
        "action_template": "Revisar clientes y líneas de producto que explican la caída antes de la próxima ruta.",
        "evidence_fields": ["growthPct", "sales", "previousSales"],
        "conflict_group": "growth",
    },
    {
        "rule_id": "SELLER_CLIENT_RECOVERY",
        "version": 1,
        "priority": 84,
        "category": "strength",
        "condition": {"metric": "recoveredClients", "operator": "gte", "value": 1},
        "message_template": "Recuperó {recoveredClients} clientes frente al período comparativo.",
        "action_template": "Registrar qué oferta o contacto reactivó esas cuentas.",
        "evidence_fields": ["recoveredClients", "droppedClients"],
        "conflict_group": "client_flow_positive",
    },
    {
        "rule_id": "SELLER_HIGH_PARTICIPATION",
        "version": 1,
        "priority": 76,
        "category": "strength",
        "condition": {"metric": "sharePct", "operator": "gte", "value": 10},
        "message_template": "Aporta {sharePct:.1f}% de la venta neta del equipo visible.",
        "action_template": "Proteger las cuentas que explican su participación sin aumentar concentración.",
        "evidence_fields": ["sharePct", "sales"],
        "conflict_group": "participation",
    },
    {
        "rule_id": "SELLER_MIX_ABOVE_TEAM",
        "version": 1,
        "priority": 72,
        "category": "strength",
        "condition": {"metric": "mixCount", "operator": "gte_context", "context": "teamMixAverage"},
        "message_template": "Trabaja {mixCount} líneas de producto, frente a {teamMixAverage:.1f} del equipo.",
        "action_template": "Conservar la amplitud de surtido y replicarla en clientes comparables.",
        "evidence_fields": ["mixCount", "teamMixAverage"],
        "conflict_group": "mix",
    },
    {
        "rule_id": "SELLER_HIGH_CONCENTRATION",
        "version": 1,
        "priority": 91,
        "category": "opportunity",
        "condition": {"metric": "top3ClientsSharePct", "operator": "gte", "value": 50},
        "message_template": "El top 3 de clientes concentra {top3ClientsSharePct:.1f}% de su venta.",
        "action_template": "Diversificar la cartera priorizando clientes medianos con compra reciente.",
        "evidence_fields": ["top3ClientsSharePct", "sales"],
        "conflict_group": "concentration",
    },
    {
        "rule_id": "SELLER_ACTIVE_CLIENTS_ABOVE_TEAM",
        "version": 1,
        "priority": 70,
        "category": "strength",
        "condition": {"metric": "clients", "operator": "gte_context", "context": "teamClientsAverage"},
        "message_template": "Atiende {clients} clientes activos, frente a {teamClientsAverage:.1f} del equipo.",
        "action_template": "Sostener frecuencia y cobertura de la cartera activa.",
        "evidence_fields": ["clients", "teamClientsAverage"],
        "conflict_group": "active_clients",
    },
    {
        "rule_id": "SELLER_NET_CLIENT_LOSS",
        "version": 1,
        "priority": 89,
        "category": "opportunity",
        "condition": {"metric": "clientBalance", "operator": "lt", "value": 0},
        "message_template": "El balance es {clientBalance}: perdió {droppedClients} y recuperó {recoveredClients} clientes.",
        "action_template": "Contactar primero los clientes perdidos de mayor venta histórica.",
        "evidence_fields": ["clientBalance", "droppedClients", "recoveredClients"],
        "conflict_group": "client_flow_negative",
    },
    {
        "rule_id": "SELLER_TICKET_BELOW_TEAM",
        "version": 1,
        "priority": 82,
        "category": "opportunity",
        "condition": {"metric": "avgTicket", "operator": "lt_context", "context": "teamTicketAverage"},
        "message_template": "El ticket es {avgTicket:.2f}, por debajo de {teamTicketAverage:.2f} del equipo.",
        "action_template": "Revisar venta cruzada y cantidad por pedido en clientes frecuentes.",
        "evidence_fields": ["avgTicket", "teamTicketAverage"],
        "conflict_group": "ticket",
    },
    {
        "rule_id": "SELLER_QUANTITY_ABOVE_TEAM",
        "version": 1,
        "priority": 68,
        "category": "strength",
        "condition": {"metric": "quantity", "operator": "gte_context", "context": "teamQuantityAverage"},
        "message_template": "Moviliza {quantity:.1f} unidades, frente a {teamQuantityAverage:.1f} del equipo.",
        "action_template": "Mantener el volumen cuidando valor por cantidad y rentabilidad.",
        "evidence_fields": ["quantity", "teamQuantityAverage"],
        "conflict_group": "quantity",
    },
    {
        "rule_id": "SELLER_OBJECTIVE_MET",
        "version": 1,
        "priority": 96,
        "category": "strength",
        "condition": {"metric": "objectiveFulfillmentPct", "operator": "gte", "value": 100},
        "message_template": "Cumple {objectiveFulfillmentPct:.1f}% de su objetivo activo.",
        "action_template": "Asegurar el cierre y documentar las palancas replicables.",
        "evidence_fields": ["objectiveFulfillmentPct", "objectiveTarget", "sales"],
        "conflict_group": "objective",
    },
    {
        "rule_id": "SELLER_OBJECTIVE_AT_RISK",
        "version": 1,
        "priority": 97,
        "category": "opportunity",
        "condition": {"metric": "objectiveFulfillmentPct", "operator": "lt", "value": 90},
        "message_template": "El cumplimiento del objetivo es {objectiveFulfillmentPct:.1f}%.",
        "action_template": "Priorizar la brecha del objetivo en clientes y líneas de producto de mayor potencial.",
        "evidence_fields": ["objectiveFulfillmentPct", "objectiveTarget", "sales"],
        "conflict_group": "objective",
    },
    {
        "rule_id": "SELLER_STRONG_CATEGORY",
        "version": 2,
        "priority": 74,
        "category": "strength",
        "condition": {"metric": "strongCategorySharePct", "operator": "gte", "value": 25},
        "message_template": "La línea {strongCategory} explica {strongCategorySharePct:.1f}% de tu venta, frente a {strongCategoryTeamSharePct:.1f}% en el equipo.",
        "action_template": "Usar la línea fuerte como puerta de entrada para ampliar el mix de líneas.",
        "evidence_fields": ["strongCategory", "strongCategorySharePct", "strongCategoryTeamSharePct"],
        "conflict_group": "category_strength",
    },
    {
        "rule_id": "SELLER_WEAK_CATEGORY",
        "version": 2,
        "priority": 80,
        "category": "opportunity",
        "condition": {"metric": "weakCategoryGapPct", "operator": "lte", "value": -2},
        "message_template": "La línea {weakCategory} representa {weakCategorySharePct:.1f}% de tu mix, frente a {weakCategoryTeamSharePct:.1f}% en el equipo.",
        "action_template": "Revisar clientes y cobertura para desarrollar esta línea de producto.",
        "evidence_fields": ["weakCategory", "weakCategorySharePct", "weakCategoryTeamSharePct", "weakCategoryGapPct"],
        "conflict_group": "category_weakness",
    },
    {
        "rule_id": "SELLER_CROSS_SELL",
        "version": 1,
        "priority": 86,
        "category": "opportunity",
        "condition": {"metric": "mixCount", "operator": "lt_context", "context": "teamMixAverage"},
        "message_template": "El mix es {mixCount}, por debajo de {teamMixAverage:.1f} del equipo.",
        "action_template": "Seleccionar una línea ausente y ofrecerla a clientes de compra frecuente.",
        "evidence_fields": ["mixCount", "teamMixAverage"],
        "conflict_group": "mix",
    },
]
